
(()=>{
  const STORAGE_KEY='ialp.clase00.interactiva.v1';
  const CONFIG_KEY='ialp.clase00.ollama.v1';
  const root=document.body;
  const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>Array.from(c.querySelectorAll(s));
  let state={answers:{},checks:{},selects:{},visited:{},updatedAt:null,currentSection:null,currentFocus:null,ui:{teacherFontSize:15,lessonFontSize:16}};
  let aiConfig={url:'http://127.0.0.1:11434',model:'',temperature:0.2};
  const toast=(msg)=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1700)};
  const loadJSON=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
  state=Object.assign(state,loadJSON(STORAGE_KEY,{}));
  state.ui=Object.assign({teacherFontSize:15,lessonFontSize:16},state.ui||{});
  aiConfig=Object.assign(aiConfig,loadJSON(CONFIG_KEY,{}));
  const save=()=>{state.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('#save-status').textContent='Guardando…';fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state})}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);$('#save-status').textContent='Guardado en BD · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}).catch(()=>{$('#save-status').textContent='Guardado local · backend no disponible';});};
  let saveTimer=null; const scheduleSave=()=>{clearTimeout(saveTimer);saveTimer=setTimeout(save,350)};
  const teacherFont=$('#teacher-font-size'),teacherFontValue=$('#teacher-font-value');
  function applyTeacherFontSize(value,{persist=false}={}){const n=Math.max(12,Math.min(22,Number(value)||15));root.style.setProperty('--teacher-chat-font-size',n+'px');teacherFont.value=String(n);teacherFontValue.textContent=n+' px';state.ui.teacherFontSize=n;if(persist)scheduleSave();}
  applyTeacherFontSize(state.ui.teacherFontSize);
  teacherFont.addEventListener('input',()=>applyTeacherFontSize(teacherFont.value,{persist:true}));
  const lessonFont=$('#lesson-font-size'),lessonFontValue=$('#lesson-font-value');
  function applyLessonFontSize(value,{persist=false}={}){const n=Math.max(13,Math.min(22,Number(value)||16));root.style.setProperty('--lesson-text-font-size',n+'px');root.style.setProperty('--lesson-input-font-size',Math.max(16,n)+'px');lessonFont.value=String(n);lessonFontValue.textContent=n+' px';state.ui.lessonFontSize=n;if(persist)scheduleSave();}
  applyLessonFontSize(state.ui.lessonFontSize);
  lessonFont.addEventListener('input',()=>applyLessonFontSize(lessonFont.value,{persist:true}));

  $$('[data-store]').forEach(el=>{
    const k=el.dataset.store;
    if(el.matches('textarea,input[type="text"],input[type="url"]')){if(state.answers[k]!==undefined)el.value=state.answers[k];el.addEventListener('input',()=>{state.answers[k]=el.value;const box=el.closest('.interactive-workspace');if(box){const st=$('.field-status',box);if(st){st.textContent=el.value.trim()?'Respondido':'Sin responder';st.classList.toggle('done',!!el.value.trim())}}scheduleSave();updateProgress();});}
    else if(el.matches('input[type="checkbox"]')){el.checked=!!state.checks[k];el.addEventListener('change',()=>{state.checks[k]=el.checked;scheduleSave();updateProgress();});}
    else if(el.matches('select')){if(state.selects[k]!==undefined)el.value=state.selects[k];el.addEventListener('change',()=>{state.selects[k]=el.value;scheduleSave();updateProgress();});}
  });
  $$('.interactive-workspace').forEach(box=>{const ta=$('textarea',box),st=$('.field-status',box);if(ta&&st&&ta.value.trim()){st.textContent='Respondido';st.classList.add('done')}});

  function updateProgress(){const fields=$$('[data-store]');if(!fields.length)return;let done=0;fields.forEach(el=>{if(el.matches('textarea,input[type="text"]'))done+=el.value.trim()?1:0;else if(el.matches('input[type="checkbox"]'))done+=el.checked?1:0;else if(el.matches('select'))done+=el.value?1:0;});const pct=Math.round(done/fields.length*100);$('#progress-bar').style.width=pct+'%';$('#progress-bar').setAttribute('aria-valuenow',pct);$('#save-status').title=`${done} de ${fields.length} actividades respondidas`;}
  updateProgress();
  $$('.auto-check').forEach(btn=>btn.addEventListener('click',()=>{const z=btn.closest('.inline-exercise'),sel=$('select',z),res=$('.auto-result',z);if(!sel.value){res.textContent='Selecciona una opción.';res.className='auto-result bad';return;}const ok=sel.value===sel.dataset.correct;res.textContent=ok?'Correcto.':'Revísalo: piensa en la acción esperada, no en la forma gramatical.';res.className='auto-result '+(ok?'good':'bad');}));
  $$('.reveal-reference').forEach(btn=>btn.addEventListener('click',()=>{const ref=btn.nextElementSibling;if(ref){ref.hidden=false;btn.textContent='Referencia visible';btn.disabled=true;ref.scrollIntoView({behavior:'smooth',block:'nearest'});}}));
  $('#btn-save').addEventListener('click',()=>{save();toast('Progreso guardado')});
  $('#btn-print').addEventListener('click',()=>window.print());
  $('#btn-export').addEventListener('click',()=>{save();const payload={curso:'IA. LA PREGUNTA',clase:'Clase 00 — Antes de aprender a responder',exportedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='IALP_CLASE_00_RESPUESTAS.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Respuestas exportadas');});

  const teacherPanel=$('#teacher-panel'),teacherMessages=$('#teacher-messages'),teacherStatus=$('#teacher-status'),teacherInput=$('#teacher-input');
  const sections=$$('.learning-section');
  const focusSequence=[];
  const focusMap=new Map();
  function cleanText(node,limit=2800){if(!node)return'';const c=node.cloneNode(true);$$('.screen-only,button,textarea,select,input,.reference-answer,.ai-feedback',c).forEach(n=>n.remove());return(c.innerText||c.textContent||'').replace(/\s+/g,' ').trim().slice(0,limit);}
  function focusLabel(el){const preferred=$('.cluster-title,.box-title,.visual-label,.lesson-kicker,.panel-label,.story-label,.causal-label,.teacher-focus-label',el);const txt=(preferred?.textContent||cleanText(el,95)||'Fragmento').replace(/\s+/g,' ').trim();return txt.length>86?txt.slice(0,83)+'…':txt;}
  const nestedFocusSelector='.known-panel,.story-frame,.transition-card,.scene-card,.spectrum-zone,.road-step,.cognitive-step,.before-card,.after-card';
  sections.forEach(sec=>{let n=0;Array.from(sec.children).forEach(el=>{if(el.matches('script,style,.page-break')||!cleanText(el,20))return;const nested=$$(nestedFocusSelector,el).filter(x=>cleanText(x,20));const units=nested.length>=2?nested:[el];units.forEach(unit=>{n+=1;const id=`${sec.id}-f${String(n).padStart(2,'0')}`;unit.classList.add('teacher-focusable');unit.dataset.focusId=id;focusSequence.push(unit);focusMap.set(id,unit);});});});
  function firstFocus(sec){return focusSequence.find(el=>el.closest('.learning-section')===sec)||null;}
  function sectionTitle(sec){return(sec&&($('h2.lesson-title',sec)||$('h2',sec))?.textContent.trim())||'Clase 00';}
  function activityIn(node){if(!node)return null;if(node.matches?.('.try-box,.form-operation-check,.operational-check,.lab-box,.worksheet,.self-check,.interactive-workspace'))return node;return node.querySelector?.('.try-box,.form-operation-check,.operational-check,.lab-box,.worksheet,.self-check,.interactive-workspace')||null;}
  function activitySnapshot(activity){if(!activity)return{exercise:'',answers:''};const clone=activity.cloneNode(true);$$('.screen-only,button,.ai-feedback,.reference-answer',clone).forEach(n=>n.remove());const exercise=(clone.innerText||clone.textContent||'').replace(/\s+/g,' ').trim().slice(0,4200);const fields=$$('textarea,select,input[type="checkbox"]',activity);const answers=fields.map((el,i)=>el.type==='checkbox'?`Campo ${i+1}: ${el.checked?'marcado':'no marcado'}`:`Campo ${i+1}: ${(el.value||'').trim()||'(vacío)'}`).join('\n');return{exercise,answers};}
  let currentSection=sections.find(s=>s.id===state.currentSection)||sections[0]||null;
  let currentFocus=focusMap.get(state.currentFocus)||firstFocus(currentSection)||focusSequence[0]||null;
  let activeArrowSource=null,activeArrowTarget=null,arrowTimer=null;
  const arrowSvg=$('#teacher-focus-arrow'),arrowPath=$('#teacher-focus-path');
  function setCurrentSection(sec){if(!sec)return;sections.forEach(s=>s.classList.remove('teacher-current-section'));sec.classList.add('teacher-current-section');currentSection=sec;state.currentSection=sec.id;$('#teacher-current').textContent=sectionTitle(sec);scheduleSave();}
  function updateArrow(){if(!activeArrowTarget||!root.classList.contains('teacher-focus-mode')||window.innerWidth<=760){arrowPath.setAttribute('d','');return;}const target=activeArrowTarget.getBoundingClientRect();if(target.bottom<0||target.top>window.innerHeight){arrowPath.setAttribute('d','');return;}const panelRect=teacherPanel.getBoundingClientRect();const sourceRect=activeArrowSource?.getBoundingClientRect();const x1=Math.max(0,panelRect.right-3);const y1=sourceRect?Math.min(window.innerHeight-18,Math.max(18,sourceRect.top+sourceRect.height/2)):Math.min(window.innerHeight-30,Math.max(30,target.top+30));const x2=Math.max(x1+36,target.left-10);const y2=Math.min(window.innerHeight-18,Math.max(18,target.top+Math.min(target.height/2,54)));const c1=x1+Math.max(44,(x2-x1)*.34);const c2=x2-Math.max(32,(x2-x1)*.22);arrowSvg.setAttribute('viewBox',`0 0 ${window.innerWidth} ${window.innerHeight}`);arrowPath.setAttribute('d',`M ${x1} ${y1} C ${c1} ${y1}, ${c2} ${y2}, ${x2} ${y2}`);}
  function setCurrentFocus(el,{scroll=false,source=null}={}){if(!el)return;const sec=el.closest('.learning-section');if(sec)setCurrentSection(sec);$$('.teacher-focus-target').forEach(n=>n.classList.remove('teacher-focus-target'));el.classList.add('teacher-focus-target');root.classList.add('teacher-focus-mode');currentFocus=el;state.currentFocus=el.dataset.focusId;$('#teacher-focus-label').textContent=focusLabel(el);activeArrowTarget=el;if(source)activeArrowSource=source;scheduleSave();if(scroll){el.scrollIntoView({behavior:'smooth',block:'center'});clearTimeout(arrowTimer);arrowTimer=setTimeout(updateArrow,360);}else updateArrow();}
  function nextFocus(from=currentFocus){const i=Math.max(-1,focusSequence.indexOf(from));return focusSequence[Math.min(focusSequence.length-1,i+1)]||null;}
  function nextExerciseFocus(from=currentFocus){const start=Math.max(0,focusSequence.indexOf(from));for(let i=start;i<focusSequence.length;i++){if(activityIn(focusSequence[i]))return focusSequence[i];}return null;}
  setCurrentSection(currentSection);if(currentFocus)setCurrentFocus(currentFocus,{scroll:false});
  window.addEventListener('resize',updateArrow);window.addEventListener('scroll',()=>requestAnimationFrame(updateArrow),{passive:true});

  const nav=$('#interactive-nav');
  sections.forEach(sec=>{const h=$('h2.lesson-title',sec)||$('h2',sec);if(!h)return;const a=document.createElement('a');a.href='#'+sec.id;a.textContent=h.textContent.trim();a.addEventListener('click',e=>{e.preventDefault();$('#ialp-index').hidden=true;const f=firstFocus(sec);if(f)setCurrentFocus(f,{scroll:true});});nav.appendChild(a);});
  $('#btn-index').addEventListener('click',()=>{const p=$('#ialp-index');p.hidden=!p.hidden;$('#ollama-panel').hidden=true});
  $('#btn-settings').addEventListener('click',()=>{const p=$('#ollama-panel');p.hidden=!p.hidden;$('#ialp-index').hidden=true});
  $$('[data-close="index"]').forEach(b=>b.addEventListener('click',()=>$('#ialp-index').hidden=true));
  $$('[data-close="ai"]').forEach(b=>b.addEventListener('click',()=>$('#ollama-panel').hidden=true));

  const urlInput=$('#ollama-url'),modelSel=$('#ollama-model'),temp=$('#ollama-temperature'),tempVal=$('#temp-value'),status=$('#ollama-status');
  urlInput.value=aiConfig.url;temp.value=String(aiConfig.temperature);tempVal.textContent=temp.value;
  temp.addEventListener('input',()=>{tempVal.textContent=temp.value;aiConfig.temperature=Number(temp.value);localStorage.setItem(CONFIG_KEY,JSON.stringify(aiConfig));});
  modelSel.addEventListener('change',()=>{aiConfig.model=modelSel.value;localStorage.setItem(CONFIG_KEY,JSON.stringify(aiConfig));});
  async function connectOllama(){aiConfig.url=urlInput.value.replace(/\/$/,'');status.textContent='Conectando…';status.className='';try{const r=await fetch('/api/ollama/models',{method:'GET'});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||('HTTP '+r.status));const models=(data.models||[]).map(m=>m.name).filter(Boolean);modelSel.innerHTML='';if(!models.length){const o=document.createElement('option');o.value='';o.textContent='No hay modelos instalados';modelSel.appendChild(o);throw new Error('Ollama responde, pero no hay modelos instalados');}models.forEach(name=>{const o=document.createElement('option');o.value=name;o.textContent=name;modelSel.appendChild(o)});if(aiConfig.model&&models.includes(aiConfig.model))modelSel.value=aiConfig.model;else{modelSel.value=models[0];aiConfig.model=models[0]}localStorage.setItem(CONFIG_KEY,JSON.stringify(aiConfig));status.textContent='Conectado · '+models.length+' modelo(s)';status.className='ok';root.classList.remove('ai-offline');root.classList.add('teacher-docked');$('#btn-settings').textContent='Configuración ✓';$('#ollama-panel').hidden=true;$('#ialp-index').hidden=true;teacherPanel.hidden=false;$('#teacher-model-badge').textContent=modelSel.value;toast('Profesor local conectado');await welcomeTeacher();return true;}catch(e){status.textContent='Sin conexión: '+e.message;status.className='bad';root.classList.add('ai-offline');return false;}}
  $('#ollama-connect').addEventListener('click',connectOllama);
  $('#teacher-settings').addEventListener('click',()=>{$('#ollama-panel').hidden=false;$('#ialp-index').hidden=true;});

  function richInline(parent,text,focusId){const re=/(\*\*[^*]+\*\*|`[^`]+`|\[[^\]]+\]\(#[^)]+\))/g;let last=0,m;while((m=re.exec(text))){if(m.index>last)parent.append(document.createTextNode(text.slice(last,m.index)));const token=m[0];if(token.startsWith('**')){const label=token.slice(2,-2);if(/^mira aquí\b/i.test(label)&&focusId&&focusMap.has(focusId)){const b=document.createElement('button');b.type='button';b.className='teacher-inline-focus';b.textContent=label+' →';b.addEventListener('click',()=>setCurrentFocus(focusMap.get(focusId),{scroll:true,source:b}));parent.append(b);}else{const b=document.createElement('strong');b.textContent=label;parent.append(b);}}else if(token.startsWith('`')){const c=document.createElement('code');c.textContent=token.slice(1,-1);parent.append(c);}else{const mm=token.match(/^\[([^\]]+)\]\(#([^)]+)\)$/);if(mm){const a=document.createElement('a');a.href='#'+mm[2];a.textContent=mm[1];a.addEventListener('click',e=>{e.preventDefault();const t=document.getElementById(mm[2])||focusMap.get(mm[2]);if(t)setCurrentFocus(t.classList.contains('teacher-focusable')?t:firstFocus(t.closest?.('.learning-section')||t),{scroll:true,source:a});});parent.append(a);}}last=re.lastIndex;}if(last<text.length)parent.append(document.createTextNode(text.slice(last)));}
  function renderTeacherText(container,text,focusId){const lines=String(text||'').split(/\r?\n/);let list=null;for(const raw of lines){const line=raw.trim();if(!line){list=null;continue;}if(/^[-•]\s+/.test(line)){if(!list){list=document.createElement('ul');container.append(list);}const li=document.createElement('li');richInline(li,line.replace(/^[-•]\s+/,''),focusId);list.append(li);continue;}list=null;const p=document.createElement('p');richInline(p,line,focusId);container.append(p);}}
  function messageActions(wrap,focusId,action){if(!focusId||!focusMap.has(focusId))return null;let focusSource=wrap.querySelector('.teacher-inline-focus');const tools=document.createElement('div');tools.className='teacher-message-tools';if(!focusSource){const fallback=document.createElement('button');fallback.type='button';fallback.className='teacher-focus-link';fallback.innerHTML='Mira aquí <span class="arrow-word">→</span>';fallback.addEventListener('click',()=>setCurrentFocus(focusMap.get(focusId),{scroll:true,source:fallback}));tools.append(fallback);focusSource=fallback;}if(action!=='closing'){const again=document.createElement('button');again.type='button';again.className='teacher-mini-action';again.textContent='Otra explicación';again.addEventListener('click',()=>guideTeacher('repeat',focusMap.get(focusId)));tools.append(again);const next=document.createElement('button');next.type='button';next.className='teacher-mini-action';next.textContent='Siguiente';next.addEventListener('click',()=>advanceTeacher());tools.append(next);}if(tools.children.length)wrap.append(tools);return focusSource;}
  function addTeacherMessage(role,content,{focusId=null,action=null,autoFocus=false}={}){if(!content)return null;const d=document.createElement('div');d.className='teacher-message '+role;const body=document.createElement('div');body.className='teacher-message-body';if(role==='assistant')renderTeacherText(body,content,focusId);else{const p=document.createElement('p');p.textContent=content;body.append(p);}d.append(body);const focusSource=role==='assistant'?messageActions(d,focusId,action):null;teacherMessages.appendChild(d);teacherMessages.scrollTop=teacherMessages.scrollHeight;if(autoFocus&&focusId&&focusMap.has(focusId))setCurrentFocus(focusMap.get(focusId),{scroll:true,source:focusSource});return d;}
  async function loadTeacherHistory(){try{const r=await fetch('/api/teacher/history');if(!r.ok)return;const data=await r.json();teacherMessages.innerHTML='';(data.messages||[]).forEach(m=>addTeacherMessage(m.role==='user'?'user':'assistant',m.content));}catch{}}
  function teacherPayload(focus=currentFocus){const sec=focus?.closest('.learning-section')||currentSection;const activity=activityIn(focus)||activityIn(sec);const snap=activitySnapshot(activity);return{title:sectionTitle(sec),context:cleanText(focus,4300),exercise:snap.exercise,answers:snap.answers,focus_id:focus?.dataset.focusId||'',focus_label:focus?focusLabel(focus):'',focus_text:cleanText(focus,4300)};}
  async function welcomeTeacher(){root.classList.add('teacher-docked');teacherPanel.hidden=false;$('#ollama-panel').hidden=true;$('#ialp-index').hidden=true;$('#teacher-model-badge').textContent=modelSel.value||'Ollama';teacherStatus.textContent='El maestro está preparando la clase…';teacherStatus.className='teacher-status';const first=focusSequence[0]||currentFocus;if(first)setCurrentFocus(first,{scroll:true});const ctx=teacherPayload(first);try{const r=await fetch('/api/teacher/welcome',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:modelSel.value,temperature:Number(temp.value),...ctx})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||('HTTP '+r.status));teacherMessages.innerHTML='';const history=data.history||[];history.forEach((m,i)=>addTeacherMessage(m.role==='user'?'user':'assistant',m.content,{focusId:i===history.length-1&&m.role==='assistant'?ctx.focus_id:null,action:'start',autoFocus:i===history.length-1&&m.role==='assistant'}));if(!history.length)addTeacherMessage('assistant',data.content||'Empezamos. Mira el bloque de la derecha.',{focusId:ctx.focus_id,action:'start',autoFocus:true});teacherStatus.textContent='Profesor activo · '+modelSel.value;teacherStatus.className='teacher-status ok';teacherInput.focus();}catch(e){addTeacherMessage('error','Ollama está conectado, pero no pude iniciar la clase: '+e.message);teacherStatus.textContent='Profesor conectado con incidencia';}}
  async function guideTeacher(action,focus=currentFocus,extra={}){if(!modelSel.value){const ok=await connectOllama();if(!ok)return false;}if(focus)setCurrentFocus(focus,{scroll:extra.scroll!==false});const ctx=teacherPayload(focus);teacherStatus.textContent='El profesor está preparando el siguiente paso…';teacherStatus.className='teacher-status';try{const r=await fetch('/api/teacher/guide',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:modelSel.value,temperature:Number(temp.value),action,...ctx,exercise:extra.exercise??ctx.exercise,answers:extra.answers??ctx.answers})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||('HTTP '+r.status));if(extra.userLabel)addTeacherMessage('user',extra.userLabel);addTeacherMessage('assistant',data.content||'Continuamos.',{focusId:data.focus_id||ctx.focus_id,action,autoFocus:true});teacherStatus.textContent='Profesor activo · '+modelSel.value;teacherStatus.className='teacher-status ok';teacherInput.focus();return true;}catch(err){addTeacherMessage('error','Error del profesor: '+err.message);teacherStatus.textContent='Error de conexión';return false;}}
  async function advanceTeacher(){const n=nextFocus(currentFocus);if(!n||n===currentFocus){toast('Has llegado al final de la clase');return guideTeacher('closing',currentFocus,{scroll:false});}return guideTeacher('next',n,{scroll:true});}
  $('#teacher-start').addEventListener('click',()=>guideTeacher('start',currentFocus||focusSequence[0],{scroll:true}));
  $('#teacher-repeat').addEventListener('click',()=>guideTeacher('repeat',currentFocus,{scroll:true}));
  $('#teacher-exercise').addEventListener('click',()=>{const f=nextExerciseFocus(currentFocus);if(!f){toast('No hay otro ejercicio en la secuencia');return;}guideTeacher('exercise',f,{scroll:true});});
  $('#teacher-next').addEventListener('click',advanceTeacher);
  $('#teacher-clear').addEventListener('click',()=>{teacherMessages.innerHTML='';toast('Vista del profesor limpiada');});
  $('#teacher-form').addEventListener('submit',async e=>{e.preventDefault();const text=teacherInput.value.trim();if(!text)return;if(!modelSel.value){const ok=await connectOllama();if(!ok)return;}addTeacherMessage('user',text);teacherInput.value='';$('#teacher-send').disabled=true;teacherStatus.textContent='Pensando…';const ctx=teacherPayload(currentFocus);try{const r=await fetch('/api/teacher/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:modelSel.value,temperature:Number(temp.value),message:text,lesson:ctx.title,...ctx})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||('HTTP '+r.status));addTeacherMessage('assistant',data.content||'No he recibido contenido.',{focusId:data.focus_id||ctx.focus_id,action:'chat',autoFocus:true});teacherStatus.textContent='Profesor activo · '+modelSel.value;teacherStatus.className='teacher-status ok';}catch(err){addTeacherMessage('error','Error del profesor: '+err.message);teacherStatus.textContent='Error de conexión';}finally{$('#teacher-send').disabled=false;teacherInput.focus();}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#ollama-panel').hidden=true;$('#ialp-index').hidden=true;}});
  document.addEventListener('pointerdown',e=>{const p=$('#ollama-panel');if(!p.hidden&&!p.contains(e.target)&&!$('#btn-settings').contains(e.target)&&!$('#teacher-settings').contains(e.target))p.hidden=true;});

  function exerciseContext(button){const activity=button.closest('.try-box,.lab-box,.operational-check,.form-operation-check,.worksheet,.self-check,.interactive-workspace')||button.parentElement;const section=button.closest('.learning-section');const lesson=(section&&$('h2',section)?.textContent.trim())||'Clase 00';const activityText=(activity?.innerText||'').replace(/Pedir pista al maestro|Entregar al maestro|Sin responder|Respondido/g,' ').replace(/\s+/g,' ').trim().slice(0,5000);const fields=activity?$$('textarea,select,input[type="checkbox"]',activity):[];const answers=fields.map((el,i)=>el.type==='checkbox'?`Campo ${i+1}: ${el.checked?'marcado':'no marcado'}`:`Campo ${i+1}: ${(el.value||'').trim()}`).join('\n');return{lesson,activityText,answers,activity};}
  async function askOllama(button,mode){if(!modelSel.value){const ok=await connectOllama();if(!ok)return;}const ctx=exerciseContext(button);const focus=focusSequence.find(el=>el===ctx.activity||el.contains(ctx.activity))||button.closest('.teacher-focusable')||currentFocus;const label=mode==='hint'?'He pedido una pista para este ejercicio.':'He entregado este ejercicio al profesor.';await guideTeacher(mode==='hint'?'hint':'review',focus,{exercise:ctx.activityText,answers:ctx.answers,userLabel:label,scroll:true});const box=button.closest('.interactive-workspace');if(box){const output=$('.ai-feedback',box);if(output){output.hidden=false;output.className='ai-feedback';output.textContent=mode==='hint'?'La pista está en el chat del profesor.':'La revisión está en el chat del profesor.';}}}
  $$('.ai-hint').forEach(b=>{b.textContent='Pedir pista al maestro';b.addEventListener('click',()=>askOllama(b,'hint'));});
  $$('.ai-review').forEach(b=>{b.textContent='Entregar al maestro';b.addEventListener('click',()=>askOllama(b,'review'));});

  const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){state.visited[e.target.id]=true;scheduleSave();}});if(!root.classList.contains('teacher-docked')){const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio);if(visible[0]&&visible[0].intersectionRatio>=.18)setCurrentSection(visible[0].target);}},{threshold:[.18,.35,.6]});sections.forEach(sec=>io.observe(sec));
  async function hydrateFromDatabase(){try{const r=await fetch('/api/state');if(!r.ok)return;const data=await r.json();const remote=data.state;if(!remote||!remote.updatedAt)return;const localTs=state.updatedAt?Date.parse(state.updatedAt):0,remoteTs=Date.parse(remote.updatedAt)||0;if(remoteTs<=localTs)return;state=Object.assign(state,remote);state.ui=Object.assign({teacherFontSize:15,lessonFontSize:16},state.ui||{});applyTeacherFontSize(state.ui.teacherFontSize);applyLessonFontSize(state.ui.lessonFontSize);$$('[data-store]').forEach(el=>{const k=el.dataset.store;if(el.matches('textarea,input[type="text"]')&&state.answers[k]!==undefined)el.value=state.answers[k];else if(el.matches('input[type="checkbox"]'))el.checked=!!state.checks[k];else if(el.matches('select')&&state.selects[k]!==undefined)el.value=state.selects[k];});$$('.interactive-workspace').forEach(box=>{const ta=$('textarea',box),st=$('.field-status',box);if(ta&&st){st.textContent=ta.value.trim()?'Respondido':'Sin responder';st.classList.toggle('done',!!ta.value.trim());}});if(state.currentFocus&&focusMap.has(state.currentFocus))setCurrentFocus(focusMap.get(state.currentFocus),{scroll:false});localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateProgress();$('#save-status').textContent='Progreso cargado desde BD';}catch{}}
  hydrateFromDatabase();
})();
